### ISSUE TITLE
create_bts_database.sh

### ISSUE THREAD

**Issue by muralithiyagarajan** [bodastage/bts-ce#22]
/r/n to be replaced with /n

**Comment by muralithiyagarajan** [comment]
unable do this correction here , unable to push from github desktop also

**Comment by erssebaggala** [comment]
You need to create a pull request

**Comment by muralithiyagarajan** [comment]
C:\Users\Administrator\Documents\GitHub\bts-ce>create_folders.bat

C:\Users\Administrator\Documents\GitHub\bts-ce>Rem create mediation directories

C:\Users\Administrator\Documents\GitHub\bts-ce>Set MEDIATION_DIR=mediation\data\cm

C:\Users\Administrator\Documents\GitHub\bts-ce>mkdir mediation\data\cm
**f was unexpected at this time.**
C:\Users\Administrator\Documents\GitHub\bts-ce>For f in (in out parsed raw) Do mkdir mediation\data\cm\f
C:\Users\Administrator\Documents\GitHub\bts-ce>

**Comment by erssebaggala** [comment]
Fixed in #33
