### ISSUE TITLE
bts-ce-v2.0.0.rc4-process_eri_rncs

### ISSUE THREAD

**Issue by muralithiyagarajan** [bodastage/bts-ce#6]
[2019-02-15 09:04:51,311] {{models.py:1736}} ERROR - (psycopg2.ProgrammingError) column "varDateTime" does not exist
LINE 6:             "varDateTime" as date_added, 
                    ^
 [SQL: '\n            INSERT INTO live_network.nodes\n            (pk,date_added, date_modified, type,"name", vendor_pk, tech_pk, added_by, modified_by)\n            SELECT \n            NEXTVAL(\'live_network.seq_nodes_pk\'),\n            "varDateTime" as date_added, \n            "varDateTime" as date_modified, \n            \'RNC\' as node_type,\n            "MeContext_id" as "name" , \n            1 as vendor_pk, -- 1=Ericsson, 2=Huawei\n            2 as tech_pk , -- 1=gsm, 2-umts,3=lte\n            0 as added_by,\n            0 as modified_by\n            FROM ericsson_bulkcm."RncFunction" t1\n            LEFT OUTER  JOIN live_network.nodes t2 ON t1."MeContext_id" = t2."name"\n            WHERE \n            t2."name" IS NULL\n        ']
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column "varDateTime" does not exist
LINE 6:             "varDateTime" as date_added, 
                    ^

The above exception was the direct cause of the following exception:

**Comment by erssebaggala** [comment]
Thanks for catching this.  I will correct it right away.  It will be available in this week's release
